version: '3.9'

services:
  mmonitoring-collector:
    container_name: lighthouse-collector
    profiles:
      - "worker"
    build: 
      dockerfile: ./docker/lighthouse/Dockerfile
      context: .
    networks:
      - mmonitoring-network
    depends_on:
      - mmonitoring-db
      - localstack

  api:
    container_name: api
    profiles:
      - "api"
    build: 
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 3000:3000
    networks:
      - mmonitoring-network
    depends_on:
      - mmonitoring-db


  mmonitoring-db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    profiles:
      - "database"
    ports:
      - '5432:5432'
    networks:
      - mmonitoring-network
    volumes:
      - mmonitoring_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


  localstack:
    container_name: localstack
    profiles:
      - "database"
    image: localstack/localstack:1.1.0
    networks:
      - mmonitoring-network
    environment:
      - EDGE_PORT=4566
      - SERVICES=s3,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - ${PORT_LOCALSTACK:-4563-4599}:4563-4599
    volumes:
      - ./docker/localstack/entrypoint:/docker-entrypoint-initaws.d
      - localstack:/tmp/localstack

networks:
  mmonitoring-network:

volumes:
  localstack:
  mmonitoring_data:
