name: Mmonitoring

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Start Localstack
        run: |
          pip install localstack awscli-local
          docker pull localstack/localstack
          localstack start -d
          echo "Waiting for LocalStack startup..."  # Wait 30 seconds for the LocalStack container
          localstack wait -t 30                     # to become ready before timing out 
          echo "Startup complete"
          ./docker/locastack/entrypoint/02-create-resources.sh

      - name: Build
        run: make build

      - name: Test
        run: make test
